# Generated by Django 5.1.1 on 2024-09-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wina', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='service',
            new_name='name',
        ),
    ]
