# Generated by Django 5.1.1 on 2024-09-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wina', '0003_transaction_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='services',
            new_name='service',
        ),
    ]
